void main () {

    try {
        int i = 0;
    }
    catch{
        print("ERROR");
    }

}