// the purpose of this file is to try test switching between functions in my try catch to ensure my frame and scope is accurate.
// in this case, I test my try in my f function by calling it in my main function. I send in a invalid string and it should print "ERROR"

void f (){
    try {
        stoi("abc");
    }
    catch{
        print("ERROR");
    }

}



void main () {
    f();
}