// The purpose of this file is to check code running before any runtime errors in my try catch
// should output 2 2

void main (){
    try {
    int sum = 0;
    for(int i = 0; i < 2; i = i + 1){
        sum = sum + 1;
    }
    string s = itos(sum);
    print(s);
    print("\n");
    print(stoi(s));
    }
    catch {
        print("ERROR");
    }
}